version: 2

models:
  - name: admission_rate
    description: List of admission rate idefied by unitid. 
      Includes the SAT score and admission rate).
    columns:
      - name: collegeid
        data_type: string
        description: ""
        tests:
          - not_null:
              severity: warn

      - name: instnm
        data_type: string
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: stabbr
        data_type: string
        description: ""

      - name: main
        data_type: int64
        description: ""

      - name: numbranch
        data_type: int64
        description: ""

      - name: preddeg
        data_type: int64
        description: ""

      - name: degree_type_description
        data_type: string
        description: ""

      - name: highdeg
        data_type: int64
        description: ""

      - name: control
        data_type: int64
        description: ""

      - name: st_fips
        data_type: int64
        description: ""

      - name: adm_rate
        data_type: float64
        description: ""

      - name: adm_rate_all
        data_type: float64
        description: ""

      - name: sat_avg
        data_type: float64
        description: ""

      - name: sat_avg_all
        data_type: float64
        description: ""

      - name: distance
        data_type: int64
        description: ""
